android.useAndroidX=true
android.nonTransitiveRClass=false
android.uniquePackageNames=false
android.builtInKotlin=false
android.newDsl=false
org.gradle.jvmargs=-Xmx4096m
org.gradle.caching=true
org.gradle.parallel=true
RELEASE_STORE_FILE=.key/app-release.jks
RELEASE_KEY_ALIAS=key0
RELEASE_STORE_PASSWORD=123456
RELEASE_KEY_PASSWORD=123456

org.gradle.tooling.parallel=true
